# 服务器
server:
  port: 8080
  session:
    timeout: 1800  # 30 分钟


# 日志
logging:
  config: classpath:log4j2.xml
  
# 数据库
druid:
  url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
  userName: root
  password: root


redis:
  host: 127.0.0.1
  port: 6379
  
# DebugInterceptor
appDebug:
  debug: true


